version: '3.9'
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatbot
      - JWT_SECRET=supertokenseguro
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=chatbot
    ports:
      - "5432:5432"
